server:
  port: 8762
  config:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
